type LogicContractSet @entity(immutable: true) {
  id: Bytes!
  _version: String! # string
  _upgrade: BigInt! # uint256
  _logicContract: Bytes! # address
  _upgradeData: Bytes! # bytes
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ModuleUpgraded @entity(immutable: true) {
  id: Bytes!
  _module: Bytes! # address
  _securityToken: Bytes! # address
  _version: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ChangeSetupCost @entity(immutable: true) {
  id: Bytes!
  _oldSetupCost: BigInt! # uint256
  _newSetupCost: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ChangeCostType @entity(immutable: true) {
  id: Bytes!
  _isOldCostInPoly: Boolean! # bool
  _isNewCostInPoly: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type GenerateModuleFromFactory @entity(immutable: true) {
  id: Bytes!
  _module: Bytes! # address
  _moduleName: Bytes! # bytes32
  _moduleFactory: Bytes! # address
  _creator: Bytes! # address
  _setupCost: BigInt! # uint256
  _setupCostInPoly: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ChangeSTVersionBound @entity(immutable: true) {
  id: Bytes!
  _boundType: String! # string
  _major: Int! # uint8
  _minor: Int! # uint8
  _patch: Int! # uint8
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
